---

version: "3.1"

services:
  memcached:
    image: library/memcached

  s3-metadata:
    image: vrancurel/zenko-memcached-module
    ports:
      - "9991"
    networks:
      - backend
    environment:
      S3METADATAPATH: /metadata
      LISTEN_ADDR: 0.0.0.0
    command: npm start

networks:
  backend:
